COURSE_CATALOG_FIELDS = [
    "institution_slug",
    "course_code",
    "subject_code",
    "course_number",
    "title",
    "description",
    "credits",
    "prerequisites",
    "learning_outcomes",
    "program_credential_association",
    "credential_type",
    "certification",
    "course_level",
    "delivery_mode",
    "campus",
    "term_availability",
    "onet_soc_codes",
    "onet_skill_elements",
    "onet_technology_skills",
    "onet_knowledge_elements",
    "onet_work_activities",
    "onet_task_statements",
    "onet_job_zone",
    "onet_alignment_notes",
    "sparse_features",
    "course_url",
    "source_url",
    "source_hash",
]

JSON_DEFAULTS = {
    "onet_soc_codes": "[]",
    "onet_skill_elements": "[]",
    "onet_technology_skills": "[]",
    "onet_knowledge_elements": "[]",
    "onet_work_activities": "[]",
    "onet_task_statements": "[]",
    "sparse_features": "{}",
}
